# **Week 2: Let's start with the data**

*Describe the work you have done this week and summarize your learning.*

## 1. Data at a glance##
After reading the data into R, I took a glimpse at the provided data. Here are my first observations:

1. The data-set consists of 183 observations relating to 60 variables.
2. Except for the variables "Age", "Attitude", "Points", and "gender" the data appear to be provided by a scale from 1 to 5. (In the print out, however, 167 rows were omitted, thus a higher scale may be possible)
3. The variable "gender", as a qualitative characteristic, are given as binary text-data in "M" (=male) and "F" (=female).
4. The variable "Age", is provided as number of years, and derived from the provided year of birth by the respondent. 

## Data-Wrangling Attempts ##

1. I printed and summarized the variable "gender":
  - the result showed that 122 respondents were female, and 61 were male.

- Describe your work and results clearly.
- Assume the reader has an introductory course level understanding of writing and reading R code as well as statistical methods
- Assume the reader has no previous knowledge of your data or the more advanced methods you are using  
